// THIS IS A BASE TEST EXAMPLE

// The cargo dbcheck will generate the test files for each stage of the course.
// Be careful; these files are not intended to be edited by students. You're free 
// to add more tests, but don't delete or edit tests generated by the testing tool

use keywords::*;