[package]
name = "sqlite-parser"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
pre-commit-hooks = "0.3.0"

[package.metadata.precommit]
fmt = "cargo fmt --check"
clippy = "cargo clippy"
